---
- hosts: 68.183.202.51
  become: true
  tasks:
  - name: install ngnix
    apt: name=ngnix state=present update_cache=yes
  - name: start ngnix
    service: name=ngnix state=started enabled=yes 
  - name: configure nginx
    template: src=templates/nginx.conf.j2 dest=/etc/nginx/sites-available/test mode=0644 #create templates for config ngnix
    notify: restart nginx
  - name: delete old link
    file: path=/etc/nginx/sites-enabled/default state=absent
    notify: restart nginx
  - name: activate test site
    file: src=/etc/nginx/sites-available/test dest=/etc/nginx/sites-enabled/test state=link
    notify: restart nginx
  handlers:
  - name: restart nginx
    service:
      name=nginx
      state=restarted